// scripts/make-images.mjs 가 만드는 파일 — 상품 id → 썸네일. 없는 상품은 먹색+금 한자로 대체. 직접 고치지 말 것.
export const THUMBS: Partial<Record<string, string>> = {
  "jeongtong": "/img/thumb/thumb_jeongtong.webp",
  "pyeongsaeng": "/img/thumb/thumb_pyeongsaeng.webp",
  "daewoon": "/img/thumb/thumb_daewoon.webp",
  "ohaeng": "/img/thumb/thumb_ohaeng.webp",
  "wealth": "/img/thumb/thumb_wealth.webp",
  "career": "/img/thumb/thumb_career.webp",
  "business": "/img/thumb/thumb_business.webp",
  "startup": "/img/thumb/thumb_startup.webp",
  "exam": "/img/thumb/thumb_exam.webp",
  "newyear": "/img/thumb/thumb_newyear.webp",
  "tojeong": "/img/thumb/thumb_tojeong.webp",
  "monthly": "/img/thumb/thumb_monthly.webp",
  "love": "/img/thumb/thumb_love.webp",
  "inyeon": "/img/thumb/thumb_inyeon.webp",
  "marriage": "/img/thumb/thumb_marriage.webp",
  "lifelove": "/img/thumb/thumb_lifelove.webp",
  "gunghap": "/img/thumb/thumb_gunghap.webp",
  "couple": "/img/thumb/thumb_couple.webp",
  "spouse": "/img/thumb/thumb_spouse.webp",
  "reunion": "/img/thumb/thumb_reunion.webp",
  "fun_tarot": "/img/thumb/thumb_fun_tarot.webp",
  "fun_dream": "/img/thumb/thumb_fun_dream.webp",
  "fun_mbti": "/img/thumb/thumb_fun_mbti.webp",
  "fun_factbomb": "/img/thumb/thumb_fun_factbomb.webp"
};
